### ISSUE TITLE
Move topic_match() to internal

### ISSUE THREAD

**Issue by contefranz** [contefranz/OpTop#4]
The function `topic_match()` is a utility function that returns a list with two `data.table` containing the informative and uninformative components. These are use by the `agg_document_stability()` function only. 

I have a couple of suggestions:

1. Move `topic_match()` to the utility function section and do not export it to the user. The designated functions will call it internally. This is to avoid confusion since there is really nothing else to do once the informative and uninformative components are computed. 
2. Convert `topic_match()` to `C++`. Even if this is "just" a utility function, its cost can't be neglected.

**Comment by mattia-** [comment]
Item 2 (c++ implementation) is in cad10f6c700c2d62eab6f70cdd763c8803430d67
